### PR TITLE
Create zh_CN.lang for 1.8 branch

### PR DESCRIPTION
**Pull request by 3TUSK**
Yeah... basically the localization on the cutting edge. 
I use the 1.7.10 translation as base and have double checked this translation in-game so that they *are* suitable.
If anyone has any further question, feel free to ask.

Edit: as I use 1.7.10 translation as base, the credits list will inherit the list in `master` branch as well.
> Id est, (alphabetical order) @3TUSK @Amamiya-Nagisa @bakaxyf @CannonFotter @crafteverywhere @IamAchang @Joccob @LYDfalse @UUUii

### CODE REVIEW

**Comment by GWYOG** [comment]
@BluSunrize  Please do not merge this PR at this moment since I think it needs further revision.

The new entries are translated pretty well. However I checked some of the old entries, and found that some of these entries in the en_US.lang has changed a lot but the corresponding Chinese translations are still the same as the 1.7.10's. They should be updated.

For example, the following lines should be updated rather than use the 1.7.10's out-of-date translations:
* [the entry about the hemp](https://github.com/3TUSK/ImmersiveEngineering/blob/zh_CN-1.8.9/src/main/resources/assets/immersiveengineering/lang/zh_CN.lang#L723)
* [the entry about the concrete](https://github.com/3TUSK/ImmersiveEngineering/blob/zh_CN-1.8.9/src/main/resources/assets/immersiveengineering/lang/zh_CN.lang#L739)
* [the entry about the electrode](https://github.com/3TUSK/ImmersiveEngineering/blob/zh_CN-1.8.9/src/main/resources/assets/immersiveengineering/lang/zh_CN.lang#L771)
* [the entry about the wiring connector](https://github.com/3TUSK/ImmersiveEngineering/blob/zh_CN-1.8.9/src/main/resources/assets/immersiveengineering/lang/zh_CN.lang#L780)
* [the entry about the metal press](https://github.com/3TUSK/ImmersiveEngineering/blob/zh_CN-1.8.9/src/main/resources/assets/immersiveengineering/lang/zh_CN.lang#L838)
* [the entry about the crusher](https://github.com/3TUSK/ImmersiveEngineering/blob/zh_CN-1.8.9/src/main/resources/assets/immersiveengineering/lang/zh_CN.lang#L1018)
* [the entry about the minerals](https://github.com/3TUSK/ImmersiveEngineering/blob/zh_CN-1.8.9/src/main/resources/assets/immersiveengineering/lang/zh_CN.lang#L1031-1032)   Also, the first "#" is missing in L1031 by carelessness.

@3TUSK  I think you should use $git diff to double-check what has changed, since the number of the total entries are so huge that it's easy for us to ignore some entries.

@BluSunrize  BTW, I am wondering why all “RF” was changed to "Flux" in the en_US.lang. Are they different? Or should we translate it to a new name as well?

**Comment by 3TUSK** [comment]
Regardless, saying *Flux* is kinda of strange for me.

**Comment by 3TUSK** [comment]
@GWYOG Hell... see my question below.
@BluSunrize Sorry but I need to confirm one question: 
does Immersive Engineering **have** its own *energy interfaces*, potentially named as "Immersive Flux" (maybe has abbreviation as IF)? 
This is important for me, as I may need to change translations, if all "Flux"s in context really refer to "Immersive Flux" rather than "Redstone Flux".
E.g.:
* [LV Capacitors, implements both CoFH `IEnergyProvider` and IE `IFluxProvider`](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.8.9/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityCapacitorLV.java#L28);
* [LV Connector, similar situation as LV Capacitors](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.8.9/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityConnectorLV.java);
* [`TileEntityMultiblockMetal`, abstract layer for metal press, excavator, arc furnace, et cetera, implements both CoFH `IEnergyReceiver` and IE `IFluxReceiver`](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.8.9/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityMultiblockMetal.java);

> Beside, IF is also the abbreviation for [AcademyCraft](https://github.com/LambdaInnovation/AcademyCraft)'s energy, Imag Flux. Cheers for the same abbreviation.

**Comment by malte0811** [comment]
Yes, IE has its own energy interface (IF, Immersive Flux), but that was added only because the RF API was updated to 1.8 quite late. The wires will convert from RF to IF and vice versa, conversion ratio is 1:1. I don't know whether @BluSunrize plans to keep this system or remove it, it is identical to RF codewise.

**Comment by BluSunrize** [comment]
Immersive Flux is and will from now on be the internal energy system of IE. As such, all values and costs are named as "IF" or "Flux". The conversion is 1:1 which is why I chose "Flux" as the word for the manual since that leaves the type of flux ambiguous.
But since I don't want to ever be slowed down by CoFH drama ever again, I will stick to my own internal energy system but support others.

Immersive Flux is our energy unit, the manual should reflect that.

**Comment by BluSunrize** [comment]
I will obviously merge this in future, but I need to get a build out tonight, so I'm skipping on this.

**Comment by 3TUSK** [comment]
I also need time on revision, so don't worry :)

**Comment by 3TUSK** [comment]
@GWYOG Theoretically [this draft](https://github.com/3TUSK/TemporaryLocalization/blob/1.8.9/assets/immersiveengineering/lang/zh_CN.lang) will be the final draft before I push another commit here. Any comments?

**Comment by GWYOG** [comment]
I think it's much better than before, well done! But it seems that this draft can be further-revised so I made a revision by myself and made a pull request to your repository, please check it out! :)

**Comment by 3TUSK** [comment]
@GWYOG Double check, so that we can make sure there is nothing wrong.

**Comment by GWYOG** [comment]
I personally believe it is good enough to become the first version of zh_CN.lang for IE 1.8.9 and added into the next release. :)

**Comment by BluSunrize** [comment]
I'll happily merge this, but maybe consider adding that one additional page for the new reinforced wooden crate before I do? =3

**Comment by 3TUSK** [comment]
@BluSunrize Here you go!

**Comment by BluSunrize** [comment]
excellent!

**Pull request merged**
