### PR TITLE
Colorable balloons and misc

### LINKED ISSUE #1650: NPE when placing a normal conveyer belt in front of a vertical one
I assume they form some type of combined block to connect them. So I had a vertical one going up and the lowest block empty. When I placed a normal belt there it crashed and now my world does not want to load anymore (obviously if it's in the render method). 

I don't get he chisel detail there as there was nothing chiseled in this area (but maybe chisel just extends some components). 

Here is the log: https://gist.github.com/mrtopf/0622f9b2dee0db282c72db3c194194f7

### PR DESCRIPTION
**Pull request by malte0811**
I just realized I probably should re-add balloon coloring to the manual, but feel free to do that yourself if you want to merge now (I don't want to do a 1-2 line commit).
Since you are currently rewriting shaders (I guess because of #1634) I might take a look at re-adding balloon shaders once you push your changes.
I know you wanted to fix #1650 yourself, but that issue was preventing me from logging into my dev server, so I fixed it.

### CODE REVIEW

**Comment by BluSunrize** [comment]
Yeah this commit is probably gonna break quite a bit.
Shaders got a massive rehaul. Might if we postpone it till I merge my shader rework into master?

**Comment by malte0811** [comment]
I won't touch shaders until your new shader code is public (if that's what you are saying). The PR as it is does not do anything with shaders, just coloring. 
Btw, does the rehaul affect gameplay or just the code?

**Comment by BluSunrize** [comment]
It changed the rendercode on smart models a little bit. That's why I don't wanna pull this yet. I think it'd be easier for me to fix merge conflicts on pulling your commit into my new render stuff rather than fixing the conflict of my new render stuff into this. =P

**Comment by malte0811** [comment]
I'll merge master into this and check that there are no problems.
Would you be opposed to adding an API interface `RotationConsumer` or something like that to allow for custom blocks using rotational energy like the dynamo? It's just an idea for basic (low-medium power, low efficiency) EU/RF conversion in IndustrialWires.

**Comment by BluSunrize** [comment]
I would not be opposed, but I don'T have time to write it atm. I can barely keep on top as is. If you wanna PR it, I'm all for it.

**Comment by BluSunrize** [comment]
Otherwise though, this commit looks good to me. I'll go merge this, the Rotation stuff can happen later I think.
But I want to get a few of those fixes out.

**Comment by BluSunrize** [comment]
In fact, I'll merge this in 2 hours, just in case there is any emergency things you wanna put in before.

**Comment by malte0811** [comment]
I have some unpushed stuff, this includes the rotational energy interface. I'll push that stuff once I am at home, that should be before 4 pm.

**Comment by malte0811** [comment]
Turns out the rotational energy was the only unpushed change I have that wouldn't require a lot of checking (I made some changes to wire models some time ago, but those would need to be tested before putting it into a release);
You can merge this now if you want to.

**Pull request merged**
