### PR TITLE
OC compat for the current meter and a lot of other stuff

### PR DESCRIPTION
**Pull request by malte0811**
It had compat before, only that it was not using drivers and had a name that doesn't work as a component name. Sorry for stealing your fix, @cobra
And I was too lazy to make a new branch, so the branch name does not resemble the content in any way

### CODE REVIEW

**Comment by cobra** [comment]
You really can't wait for anything, can't you? -.-

**Comment by malte0811** [comment]
I don't really have anything to do right now...

**Comment by elifoster** [comment]
>You might see more than one bug that you’d like to fix. Be sure that if you do, submit them as two separate pull requests. A lengthy pull request is unlikely to be dealt with quickly. It could be difficult for the original developer to try and follow your steps. 

[Just saying](http://readwrite.com/2014/07/02/github-pull-request-etiquette)

**Comment by BluSunrize** [comment]
Don't pull that shit on my contributors. I trust them, and I value their support, and so should you.

**Comment by malte0811** [comment]
Thanks

**Comment by malte0811** [comment]
Please don't make a release yet, i have 2 commits on my tmp branch that i would like to go into the next version.

**Comment by BluSunrize** [comment]
I'm not I just wanted to pull this finally and update the patron lists. No 1.7 work happening, lol

**Pull request merged**
