### PR TITLE
Added posibillity to add graphit electrodes

### PR DESCRIPTION
**Pull request by chaos234**
Hey @BluSunrize ,

I know that you did not support your 1.7.10 version so I have made a small feature change to it.
I hope it is ok for you because I (only) heared that it was in the past possible to automaticly replace
the Graphite Electrodes.

As you can see, I have added the necessary lines of code and I hope it is ok for you, that I have choosen
the left and the right side from the slag output and the top side from the electrodes.

What I have not changed is the model so that you can see where the inputs for the GEs are. If it is possible I am glad to have an edited model for this but if it doesn't matter I hope that you'll merge this in your 1.7.10 branche, compile and release it as official new version.

I hope also that I can maintain this Mod for 1.7.10, providing you with eventually new features and bugfixes (if there are any). Means that I'll give my best and test what I have written and if all works fine
you'll get the PR to merge an recompile it as new official version if this is ok for you.

If you have any questions to this feel free to ask but as long as I don't have your official permissions I will not release this fix (only private use for me, currently).

Greetings
Chaos234
(MC: Chaoschaot234)

### CODE REVIEW

**Comment by BluSunrize** [comment]
No, I'm sorry, but I won't be merging that. The automatic management of graphite electrodes was disabled on purpose. I made that balance change in full knowledge of what I was doing.

Also I don't really intent for IE in 1.7.10 to be maintained anymore. That just further encourages stagnation.

I appreciate the effort you put into the code and the PR, but I'm afraid I won't be pulling this.

**Comment by BluSunrize** [comment]
So you decided to be a tough guy in my IRC channel and threaten me while I was away, huh?
Well here's your reply since you chose to leave right after.

This is what you said on IRC:
>@BluSunrize|away - I have checked github and as long as you don't have any license.txt you must either remove IE or make it private otherwise it is under the opensource license (please read the TOS from github for more information). Means that I am allowed to fork it, make changes and also make them public (ok, they are already public so this doesn't matter). If you go against this then I'll write a message to gtihub administration and IE will be instantly removed from github as long as you don't follow there TOS - I am sad that I must go this was but I have thinked about it and YES I will go this way. Means also that I am out here but I am on other channels to if you want to chat with me. So Version 0.7.8 with optional GE-Automation will be out on my repository - cheers"

Picture evidence for good measure:
http://puu.sh/tIlm1/a165ac2201.png

And here is githubs stance on licenses (thank you to LuigiHutch for pointing that one out)
https://help.github.com/articles/licensing-a-repository/

Which very clearly says that yes, you may fork my repo, but without a license, it clearly states that
>[...]  no one may reproduce, distribute, or create derivative works [...]

So next time you try to screw someone over with the small print? Read it fully, you prick.

**Comment by chaos234** [comment]
@BluSunrize - So you wanted it and know I have send an ticket to the GitHub Staff which means either you are following the TOS or maybe this Repro get deleted from Github.

Don't try to think that you are god because I am right that I can fork and redistribut any modified version of this forked repro as long as I am follow the Githubs License (because you haven't any license yet and adding one now take affect for any changes made in the future but will not affect any changes in the past).

And if LuigiHutch thinks that he knows the hole TOS of github by simply giving you one small link then he and also you are the pricks and not I.

My release will come, compleatly officially.

**Comment by KnightMiner** [comment]
No license defaults to "All right reserved", not "public domain". General copyright laws, read up on them

**Comment by TTFTCUTS** [comment]
Ok, so let me get this straight - you're threatening someone to surrender their intellectual property despite the license defaulting to all rights reserved. Good luck with that.

**Comment by chaos234** [comment]
@KnightMiner - And this is not allowed on Github so deal with it.

**Comment by iChun** [comment]
@chaos234 wow, rude.

**Comment by yannick9906** [comment]
@BluSunrize @KnightMiner Keep in mind that GitHub only allows to upload/host repositories which are open-source. If you want "normal" copyright to apply you should remove your project from github.
A repository without a license is NOT open-source and you should add a LICENSE.txt to your repositories to 
avoid this in future.

https://opensource.org/faq#avoid-unapproved-licenses
> **Can I call my program "Open Source" even if I don't use an approved license?**
Please don't do that. If you call it "Open Source" without using an approved license, you will confuse people. This is not merely a theoretical concern — we have seen this confusion happen in the past, and it's part of the reason we have a formal license approval process. See also our page on license proliferation for why this is a problem.

**Comment by BluSunrize** [comment]
Dude. You're not achieving anything. Stop while you are even still slightly above water.

I don't consider myself a god, not by a longshot. But you're making yourself look like an asshat infront of a big, very loving and comfortable community.
People would have accepted you with open arms if you made your own project. The Reddit is great about that for instance, people are supporting and enjoy to see new ptojects come to fruition.

Instead, you set out to devalue and deface someone elses work. To what end?! Just because the mods balance doesn't agree with you, and my statement of "I don't want to continue this mod on 1.7"?
And now you're trying to blackmail me about this or what? There is basically no positive outcome for you here mate, just give it up.

**Comment by TTFTCUTS** [comment]
@yannick9906 - From what I can discern from reading it, the only additional things I see from public repos is that people are allowed to fork and view within the site, presumably for the purposes of submitting pull requests. It doesn't say that they are allowed to distribute that work outside of github, or that the repo owner has any obligation to accept any requests.

**Comment by chaos234** [comment]
@BluSunrize - That words ... who has removed the possibillity to replace GEs automaticly in 0.6.3 for personal reason because you don't like full automisations?

Sorry, but you are giving yourself the punch for this.

Notice for you: I will made it as an own new project referring to you as original author. It will be opensource like it is here so anyone can fork it. So it will definitly go on reddit and other pages.

**Comment by yannick9906** [comment]
@TTFTCUTS That's right. I just wanted to clarify some things here and give a kind advice to @BluSunrize to add a license so everybody know, what he/she is allowed to do and not to do. (https://choosealicense.com/ is a good page by github to choose one)

**Comment by BluSunrize** [comment]
Any code taken from me is a violation- And of Damien's textures used are a violation.
The fact that it's not a fork technically allows me to file a DMCA takedown against it right this instant.

Are you sure this is a battle you can win, sir? Because to me it looks like you're out of options.

Give it up, and we'll forget the whole matter. It's in everyones best interest.
(Like seriously. The notifications I'm gettign in IRC, discord, twitter and here are annoying. Can't get work done like this.)

**Comment by nvx** [comment]
For reference https://github.com/chaos234/ImmersiveEngineering2 is a non-fork copy of this repository created ~10 minutes ago.

Might be worth getting the letter writing over and done with, bit hard to comment when ones GitHub account is suspended for DMCA violations.

**Comment by BluSunrize** [comment]
As I said, yes, I could easily file a DMCA. But I'm giving @chaos234 the choice here to have it end cleanly.
There is no need for (pseudo-)legal action jsut yet.
If they kill off that repo and takes back their hollow threats, I'm more than happy to let this blow over.

**Comment by chaos234** [comment]
Ok, I will remove the opened own IE2 repro (sorry for that, was a knee-jerk reaction).

But then please give me the possibility to accept issues (this tab did not exists yet in the forked version) and the options for releases. And yes I am exploded/frusted (is this an existing word in the gnl. vocab?) and so far but you should understand me too.

It is rly not that bad to have someone which wants to fully maintain old things and sometimes it is good, sometimes not. So please, please re-think about your choise and also I promise that I won't breake the entire mod and you can also take a look on what I have changed.

The IE2 Repro should be removed within the next few minutes. Sorry for the trouble.

**Comment by Havvy** [comment]
The Github license allows for forking and viewing the code. It does not allow for modifying and then redistributing it. @chaos234, you're in violation of copyright laws, and @BluSunrize is correct that they could file a DMCA.

-- Another programmer who knows copyright law and doesn't care about either of y'all.

**Comment by chaos234** [comment]
@BluSunrize - Well done (ignoring other comments).

**Comment by BluSunrize** [comment]
Right, see? That's a far more sensible solution to filing a takedown.

Despite all of this, or maybe even because of it, my stance has not changed. IE for 1.7.10 is not receiving any further updates, and I am not assigning any maintainer for the project.

And after the stunts you pulled? Definitely not you. Never you. Blackmailing is not how you apply for a job.

Now, this topic is over, I remain adamant on my statement, and we can drop the damn topic now. Okay? Okay. Good.

**Comment by chaos234** [comment]
@BluSunrize - After all what happend it is okay and as stated privatly in/on IRC to you for the others again for causing some trouble of my knee-jerk reaction ~ Cheers

**Comment by KitsuneAlex** [comment]
Wow this is not cool

**Pull request closed without merging**
