### PR TITLE
Full Ukrainian

### PR DESCRIPTION
**Pull request by MEGATREX4**
Full translation of the manual
Full translation of the items
Formatting manual text

### CODE REVIEW

**Comment by BluSunrize** [comment]
Why do you keep closing your pullrequests?

**Comment by MEGATREX4** [comment]
the team and I noticed some small bugs, it is desirable to fix them so that it does not spoil the impression of the game, I will return the pull request soon

**Comment by MEGATREX4** [comment]
We apologize for the inconvenience.

**Comment by MEGATREX4** [comment]
Once again, my team and I apologize for any inconvenience

**Review by hnufelka — APPROVED** [review]

**Comment by BluSunrize** [comment]
For the record: You do not need to close a pullrequest for that. Just write "WIP" in the title if you aren't done! =P

**Comment by MEGATREX4** [comment]
Oh well, now I'll know

**Pull request merged**
