### PR TITLE
Reduce size of recipes in PacketBuffer's

### PR DESCRIPTION
**Pull request by malte0811**

### CODE REVIEW

**Comment by BluSunrize** [comment]
I understand that this is a quick fix to the recipes added by IE, but shouldn't issues with vanilla shaped recipes be handled in Forge instead?

**Comment by malte0811** [comment]
No, Forge servers need to be compatible with vanilla clients and vice versa. With this changed format that isn't (easily?) possible.

**Comment by BluSunrize** [comment]
Ah! I was unaware/ignorant of the fact that Forge and Vanilla required compatability.
That said, Compressed Recipes could still be a part of Forge's framework, much like ShapedOre and ShapelessOre recipes were in past iterations, no?
I'm not looking to dismantle this PR, I'm all for reducing the packet size, I'm just thinking that it would be good to standardize this across the modded community!

**Comment by BluSunrize** [comment]
@malte0811 Are you still looking to have this implemented?

**Comment by malte0811** [comment]
Probably some parts of it, but not everything. Some things are optimized much better in RecipeBuffers than they can be here, but other things I can't really influence from outside IE. I'll remove the parts that I don't want any more when I have some time.

**Pull request closed without merging**
