### PR TITLE
Conveyor belt fixes

### LINKED ISSUE #1142: [1.8.9][possible bug] dropping conveyors not dropping into some vanilla inventories below it
the Dropping conveyors don't seem to drop into some vanilla inventories, this includes vanilla furnaces top slot for input, trapped chests (which normal conveyors don;t insert into) to name a couple. They do however drop into hoppers are far as i can tell. Is this intended? or did a find a bug?

### PR DESCRIPTION
**Pull request by malte0811**
Fixes #1142 and #1140

### CODE REVIEW

**Comment by malte0811** [comment]
I pinged you in a comment on an experimental commit a few days ago, did you see that one?

**Comment by BluSunrize** [comment]
Right yeah, I forgot to respond to it. I'd say go for it as long as it emulates vanilla placement logic entirely. Just so that it's not missing a call.

**Comment by malte0811** [comment]
I think I copied the code from the vanilla logic, modified the broken parts and compressed some checks in the beginning. I don't know when you want to build, but I probably won't be at my computer until ~4pm, so if you want to build before that please check that I didn't delete anything. The relevant method is `ItemBlock.onItemUse`.

**Comment by BluSunrize** [comment]
I'm gonna still do work on stuff as well, don't worry. Build won't be early.

**Pull request merged**
