### PR TITLE
Restart connection raytracing

### PR DESCRIPTION
**Pull request by cobra**
This should remove nearly all unexpected "connection obstructed" messages due to failed connection validation, see #392. The only exception are blocks with an irregular model like wall mounts - we can only check for bounding boxes, not visible models.

ToDo before or after merging: remove debug logging and threshold variable

### CODE REVIEW

**Comment by BluSunrize** [comment]
thank you <3

**Comment by cobra** [comment]
Remember to remove the debug stuff (logging, adjustable threshold) before releasing 0.6. I left it in to allow easy testing without having to use the debugger each time.

**Comment by BluSunrize** [comment]
Wait, if I remove the debug threshhold, what else do I take out? it's actively used in the conditions, isn't it?

**Comment by cobra** [comment]
replace it by the value, there's no need to have that as a variable besides allowing you to change it during runtime for testing purposes. I didn't find any situation needing lower thresholds, but maybe someone else finds one where ±0.4 would be necessary to allow a valid connection.
Remove it like this: https://github.com/cobra/ImmersiveEngineering/commit/078e254eeed3108136b5deaefaa4ceae504db265

**Comment by BluSunrize** [comment]
Ah, right kk =P

**Pull request merged**
