### PR TITLE
translate pt-br

### PR DESCRIPTION
**Pull request by felipeboff**
it took about a week to complete

### CODE REVIEW

**Comment by BluSunrize** [comment]
Why'd you close it?

**Comment by felipeboff** [comment]
> @BluSunrize  Why'd you close it?

Corrections and adjustments. I will open it again when finished.

I don't want to spam with my adjustments and corrections.

**Comment by BluSunrize** [comment]
Then I shall mark this as a draft. That way it remains open. Let me know when it's ready to merge.

**Comment by BluSunrize** [comment]
I have picked these changes into our 1.15 branch:

https://github.com/BluSunrize/ImmersiveEngineering/commit/623b4f2eadd78a23dd13b321c6208682759c0d97

It will be merged into 1.16 and 1.16.3 from there.

Thanks for the contribution =)

**Pull request closed without merging**
