### PR TITLE
Update CC:T integration to 1.20.1

### PR DESCRIPTION
**Pull request by SquidDev**
This is a couple of fixes to update ComputerCraft/CC: Tweaked to match the 1.20.1 API.

 - Remove `TaskCallback`, as that is now exposed in the public API.
 - Fix arguments not being marked as escaping when running off-thread.
 - Replace `ItemStack`/`FluidStack` conversion with CC's detail providers. This should be backwards compatible (the fields exposed appear to match), but happy to revert this if preferred!

### CODE REVIEW

**Comment by BluSunrize** [comment]
Sorry, we only do bugfixing on 1.20.1

New features are 1.20.4 only. If you would like to, you update to that version, however?

**Comment by SquidDev** [comment]
Ahh sorry, wasn't sure so just targetted the default branch! Yep, will update the branch and retarget the PR.

**Comment by SquidDev** [comment]
I've pushed something which partially works, with the exception that the code doesn't subscribe to the `RegisterCapabilitiesEvent` event. It's a bit tricky for compat modules to subscribe to this event for a couple of reasons:

 1. The event is fired during the registry stage, so before compat modules are loaded. And we can't move module loading any earlier, as the config values haven't been loaded yet.
 2. The mod event bus isn't accessible to compat modules. We could definitely pass it around as an argument, but didn't feel worth making this change without addressing 1).

Both are definitely fixable[^1], but I didn't really feel comfortable making any changes without further discussion. 

[^1]: I tested by switching CC to be an `EarlyIECompatModule`, but that's probably not a good solution.

**Comment by BluSunrize** [comment]
...yeah this is why I assigned @malte0811 to the original issue, because I don't know how to get those capabilities in there anymore since the old event has stopped existing.

**Comment by SquidDev** [comment]
Ahh sorry, I hadn't spotted #5914! Definitely agreed that this isn't high priority, so happy if you want to close this and use it as a reference for a future fix :).

**Comment by SquidDev** [comment]
Thank you both!

**Pull request merged**
