### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by malte0811**
Improved rendering memory usage by not creating a new TE every time an item that belongs to a block with a TE is rendered
fixed a crash when measuring loss between non-existing points
Why the hell would the villager buy emeralds with metadata 2, 7 or 18? This was very confusing when I was testing my villager fix :smile:
@cobra hasn't answered about the slot id's in OC compat yet (I asked about a week ago), if you want to release a new version, just tell me and I will make those changes myself.

### CODE REVIEW

**Comment by BluSunrize** [comment]
Can you write the fix? I don't wanna wait on @cobra any longer.

**Comment by cobra** [comment]
I'm out for now.

**Comment by BluSunrize** [comment]
Fair enough

**Comment by malte0811** [comment]
I'll write it tomorrow, I have had a pretty exhausting day and while that change is pretty easy, I'd rather not push any more bugged code than I already have.

**Comment by BluSunrize** [comment]
roger that

**Comment by BluSunrize** [comment]
I'll pull this now to get some extra work done and not risk merge issues, so the additional fixes will be a new PR.

**Comment by Cracks777** [comment]
Not Trying to be Pushy but do you have a ETA for the next release?

**Comment by BluSunrize** [comment]
But you are being pushy, which is quite rude. So sit down and wait patiently like everyone else.

**Comment by Cracks777** [comment]
LOL ROTFLMAO Fuck Dontaing my money to this RUDE ASSHOLE

**Comment by Cracks777** [comment]
Not like you cant get the Patron builds online anyway.

**Comment by BluSunrize** [comment]
Although you deleted your comments, I very much saw them. If you dislike how my patron system operates, that is your personal opinion. It's a voluntary donation and I very much appreciate all the people that actually do it.
You're being disrespectful towards the kindness of those people, which is a shame.

**Comment by Cracks777** [comment]
Your Attitude toward people is a SHAME, and yes i know you saw the comment, thats why i deleted them. it was intend for you only. every time someone post something on here you have a smart ass remark to make about it, and i had pledged to your work but with an attitude like yours i surprised anyone does. a question is a question theres no reason to act like a child.

**Comment by BluSunrize** [comment]
I get these question /every/ /damn/ /day/. And at least twice. On twitter, IRC and elsewhere. Even I get to the point where that is immensely exhausting. My answer always stays the same, "it's done when it's done", and the incapability of people to accept that statement is irritating.
The reason why I'm a smart ass about it? Because it makes it bearable. And because it's entertaining to anyone but the person on the receiving end. 
Once again, I defer to the argumentation of: Us mod devs don't owe you anything. We invest countless hours into these projects out of our own enjoyment of it. If we stop enjoying it, the projects stop existing. We don't get payed for any of it, and, while yes, I have a Patreon based income, I do hold up to all pledge rewards promised to my patrons. Everyone who donates for revolvers gets approached by me at the start of each month, asking what skin they want and what their UUID is. And everyone who pledges for dropbox access and actually supplies eme with their DB email is supplied with access from the point of their first successful pledge until they stop pledging.

**Pull request merged**
