### PR TITLE
getRandomMineral is actually random

### PR DESCRIPTION
**Pull request by marcin212**
before fix: http://ideone.com/KWhkBc
after fix: http://ideone.com/C2xmaQ

If "weight" is smaller then 0, then I can find only Iron, because Iron is first on mineral list.

### CODE REVIEW

**Comment by BluSunrize** [comment]
Same should be achieveable with Math.abs() if I'm not mistaken?

**Comment by marcin212** [comment]
yes

**Comment by marcin212** [comment]
I changed it.

**Comment by BluSunrize** [comment]
woops.

**Pull request merged**
