### PR TITLE
World save data fixes

### PR DESCRIPTION
**Pull request by cobra**
Makes loading world save data a bit more reliable, mainly countering missing wires. The commit messages and the issues have all the details.

### CODE REVIEW

**Comment by BluSunrize** [comment]
Let's hope this actually fixes stuff .~.

**Comment by cobra** [comment]
I did rather extensive testing on that in addition to the debugging to find what was causing these weird behaviours and couldn't see anything getting worse…

**Comment by XFactHD** [comment]
Did you also test what happens when performing a debug crash without saving by pressing escape?

**Comment by cobra** [comment]
This doesn't change anything on that end, saving works exactly the same as before. I changed some cases in which that data wasn't loaded, completely ignoring what was saved.

**Comment by XFactHD** [comment]
Ok, nevermind.

**Pull request merged**
