### PR TITLE
update Japanese translation

### PR DESCRIPTION
**Pull request by karakufire**

### CODE REVIEW

**Comment by koh-gh** [comment]
I suggest some improvements.

- Hoes are translated as 'クワ' in Vanilla. Therefore, it is preferable that steel hoe be translated in the same way.(Use katakana translation)
- Liquid creosote is translated as 'クレオソートオイル', while bucket creosote is translated as 'クレオソート油'. They need to be the same.

And, there are some that haven't been translated yet. Are there any plans for additional translations?

**Comment by karakufire** [comment]
Thank you for reviewing.
These 2 points you raised are correct and I'll change them.
And untranslated entries, 
* shaders' names, "Oresome": Because I couldn't find suitable translation for them, I keep as is in respect for original.
* ie.manual.entry.mineralsDimInvalid, ie.manual.entry.mineral_main: Because I could not check where them would be used.

Untranslated shader's description(excepts "waaagh") is simply I forgot to translate.

**Comment by BluSunrize** [comment]
Is this ready to be merged?

**Comment by koh-gh** [comment]
I have no problem.

**Comment by karakufire** [comment]
I'm OK

**Comment by BluSunrize** [comment]
Thank you =)

**Pull request merged**
