### PR TITLE
Czech language file for IE 1.19.2 [COMPLETE]

### PR DESCRIPTION
**Pull request by RomanPlayer22**
Finally. Czech translation made by me

### CODE REVIEW

**Comment by BluSunrize** [comment]
I won't be merging this while it's marked as WIP
Please notify in this PR when its complete

**Comment by RomanPlayer22** [comment]
@BluSunrize no longer WIP; can you merge please? Thank you.

**Comment by RomanPlayer22** [comment]
Still, waiting for this to be approved.

**Comment by BluSunrize** [comment]
Thanks =)

**Pull request merged**
