### PR TITLE
Added Telecommunication connector and wire

### PR DESCRIPTION
**Pull request by marcin212**
c69b75803de03d9bfc66597164ed45ce

### CODE REVIEW

**Comment by BluSunrize** [comment]
Woh woh woh
Not like this. Make it an addon.
I only provided API changes for this, not native support.

**Comment by marcin212** [comment]
The point is that the API is... not flexible enough.
Example: I spent eight hours figuring out ways around some limitations, but gave up on cable support. I can't add a networking cable for OpenComputers in a simple, meaningful and actually useful way, because of the limitations you put on the Wire Cutters.

**Comment by BluSunrize** [comment]
Well IE also wasn't ever designed with this in mind. I'll add some API fixes to my ToDo, but native OC support is kinda past the point

**Comment by alucard87pl** [comment]
That was kinda the point, though. Since the API did not provide the hooks to add these externally in an easy way, a direct pull request adding the needed features seems the next logical step.

**Comment by BluSunrize** [comment]
That is why I'm planning those hooks >_>

**Pull request closed without merging**
