### PR TITLE
[1.10] Adds support for Mystical Agradditions

### PR DESCRIPTION
**Pull request by SoftPoison**
As per title.

Do note, due to the way Mystic Agradditions handles insanium and the tier 6 inferium crop, it may break a little in future versions, but that's unavoidable

### CODE REVIEW

**Comment by BluSunrize** [comment]
Is this for 1.10 or 1.11?

**Comment by malte0811** [comment]
I feel like the compat should be added on Mystic Agradditions side due to requiring even more reflection than M. Agriculture when done from IE's side. In the end it is @BluSunrize's decision though. Pinging @BlakeBr0 (the author of Mystic Agriculture/Agradditions).

**Comment by SoftPoison** [comment]
It's for 1.10 as the PR as that's what #2156 was merged into, but I have tested it to also be compatible with 1.11

**Comment by BluSunrize** [comment]
I didn't really plan on another 1.10 release, that's why I'm asking.
I'm hoping to move towards 1.12 rather quickly this time so as not to get left behind.

**Comment by SoftPoison** [comment]
Ah, fair enough. I could resubmit the PR to the 1.11 branch if you would prefer

**Comment by BluSunrize** [comment]
I'm with Malte on this, develop input please, before we start reflecting *everything*

**Comment by BluSunrize** [comment]
I renamed branches, which resulted in this closing. Sorry.

**Comment by malte0811** [comment]
The author of Mystical Agradditions doesn't like the idea, see the above issue (#2536).

**Pull request closed without merging**
