### PR TITLE
Mini last minute PR

### PR DESCRIPTION
**Pull request by malte0811**
Fixed insulating glass and ported the potion ID fix/un-recursion (which apparently isn't even used anymore because potions have String ID's now... Noticed that after pushing).

### CODE REVIEW

**Comment by BluSunrize** [comment]
oh shit.

this got closed by me deleting the 1.8.9 branch.

**Comment by malte0811** [comment]
Why did you close this?

**Comment by BluSunrize** [comment]
My bad. Should have pulled it before the name change. Didn't think ahead there.

**Comment by malte0811** [comment]
I'll make a new one.

**Comment by BluSunrize** [comment]
I fixed it.

**Pull request closed without merging**
