### PR TITLE
Add ForgeMultipart compat

### PR DESCRIPTION
**Pull request by miuirussia**
Please, add ForgeMultipart support

### CODE REVIEW

**Comment by AEnterprise** [comment]
can this even work? i know carpenters blocks don't work with these cause of the special rendering

**Comment by miuirussia** [comment]
Tested and working)

**Comment by XFactHD** [comment]
@AEnterprise it works (I tried it by simply adding the decorative blocks to FMPs multipart.cfg) but the covers (at least in this aproach) are unable to disconnect FMP cables like OCs networking cables.

**Comment by BluSunrize** [comment]
Multiparts are a thing now anyway. I forgot abotu this one, and jsut added them when Damien bugged me xD

**Pull request closed without merging**
