### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by 3TUSK**
Proudly appreciate to @crafteverywhere, @bakaxyf, @IamAchang, @UUUii, @CannonFotter as well as @Joccob for their suggestions, work or review on zh_CN.lang of IE. There are some other people who don't have Github account but provide me with assistance in other way, and I will provide the list if you need.
Special revolver's name finally didn't get translated.

I double checked it and I believe that this one will be *fine*. If you do need a person with authority to review it like [this] (https://github.com/BluSunrize/ImmersiveEngineering/pull/58) or [this] (https://github.com/BluSunrize/ImmersiveEngineering/pull/77), I will say @crafteverywhere, one of the managers of Buildcraft's, Forestry's, Railcraft's as well as Factorization's localiztaion repository. I hope he can get some seconds to look at it.

In addition, I added an entry for tooltip of drill when no fuel is in the drill.

Thanks a lot for bringing such a great mod to us!

### CODE REVIEW

**Comment by 3TUSK** [comment]
Also, I noticed that two tables in biodiesel part in the engineer's manual doesn't get translated. I think [somewhere] (https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/api/DieselHandler.java#L116) should use ````getItem().getItemStackDisplayName()````

**Comment by BluSunrize** [comment]
Sorry, but I had to clean my repo
Could you please resubmit the PR?

**Comment by 3TUSK** [comment]
As long as you finished cleaning up. No problem.

**Comment by 3TUSK** [comment]
Is okay to make a PR now?

**Comment by BluSunrize** [comment]
Yep, it's call clear now

**Comment by 3TUSK** [comment]
I will :)

**Pull request closed without merging**
