### PR TITLE
some API modifications

### PR DESCRIPTION
**Pull request by marcin212**

### CODE REVIEW

**Comment by BluSunrize** [comment]
I already told you I'm rewriting it myself. Give me more than 3 hours maybe?

**Comment by BluSunrize** [comment]
In fact, I've already finished it, and I'm commiting atm.

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/a111815e24b5fbbec479251bcc9bccce270ed3e9

And there you go.
Now you can make it an IE addon.

**Comment by marcin212** [comment]
\o/

**Pull request closed without merging**
