### PR TITLE
Fix UUID for my revolver!

### PR DESCRIPTION
**Pull request by warlordjones**
A case of mistaken identity, it seems!

### CODE REVIEW

**Comment by BluSunrize** [comment]
So how long has that been an issue? xD

**Comment by warlordjones** [comment]
Not sure. I hadn't bothered to set username in my development environment (only place I've been 'playing' lately) until now... :D

**Comment by BluSunrize** [comment]
Fair!

**Comment by BluSunrize** [comment]
probably should have renamed that commit. Woops.

**Comment by warlordjones** [comment]
No git history I've even looked at ever remains clean for long :p

**Pull request merged**
