### PR TITLE
zh_cn manual translation added

### PR DESCRIPTION
**Pull request by masakitenchi**

### CODE REVIEW

**Comment by BluSunrize** [comment]
I sure wish people would listen when we say "please put pullrequests against 1.14", because having to merge these manually sucks.

**Comment by masakitenchi** [comment]
> I sure wish people would listen when we say "please put pullrequests against 1.14", because having to merge these manually sucks.

I wonder if changing the branch to 1.14 could simplify your work. And I was too hurry to find any "PR to 1.14 pls"-like comment. My apologize. Maybe write it explicitly in README.md would let future potential contributors have less problem.

**Comment by masakitenchi** [comment]
Okay. I barely know how to code in java, and there are some problems when trying to send PR to 1.14. Should I fork another 1.14 branch and send PR from there?

**Comment by BluSunrize** [comment]
No, I can pull this is manually later.

**Comment by BluSunrize** [comment]
I have merged this manually:

https://github.com/BluSunrize/ImmersiveEngineering/commit/947fb1c6da8d5127f07a384e5c520a905b583833

**Pull request closed without merging**
