### PR TITLE
Updating the Russian translation 1.15 (now it will work).

### PR DESCRIPTION
**Pull request by Sergo467**

### CODE REVIEW

**Comment by BluSunrize** [comment]
Now, I don't speak Russian, but your new translation file actually seems to remove a lot of stuff? Advancements are no longer translated, for one. Is this intentional?

**Comment by Sergo467** [comment]
> Now, I don't speak Russian, but your new translation file actually seems to remove a lot of stuff? Advancements are no longer translated, for one. Is this intentional?

I found that the old translation file was completely outdated and did not work on the new versions. I took the English translation as a basis and started almost from the beginning. An old translation was used to speed up the process. In the future, I plan to translate everything completely. I also found that the translation of the engineer's book was placed in a separate folder. I plan to translate it too.

**Comment by BluSunrize** [comment]
I'm reassigning this PR to the 1.14 branch, and merging it there, since 1.14 is the branch we develop against.

**Comment by BluSunrize** [comment]
okay, that was apparently not a great idea.

**Comment by BluSunrize** [comment]
guess I'll just have to fuckin' cherrypick it.

**Comment by BluSunrize** [comment]
also, how the hell is this causing merge conflicts

**Comment by BluSunrize** [comment]
I'll just pull this in manually.

**Comment by BluSunrize** [comment]
Changes have been cherrypicked into 1.14, and will be merged into 1.15 as well:

https://github.com/BluSunrize/ImmersiveEngineering/commit/a50b13a3c2435dcb53f5196db8cebef7bb74d83c

**Pull request closed without merging**
