### PR TITLE
Fix Revolver Perk Bug

### PR DESCRIPTION
**Pull request by gorberto**
What this PR does:
- Updates the indexes of items to check in the crafting matrix when applying perks to the revolver

Address https://github.com/BluSunrize/ImmersiveEngineering/issues/5452

### Items with Perks
barrel
drum
hammer
### Before (only the drum perks are applied)
before
### After (all perks are applied)
after

### CODE REVIEW

**Comment by malte0811** [comment]
The file you changed is automatically generated and will be overwritten the next time datagen runs (e.g. in the GH action runs once they complete). Instead you need to change the code that generates the file, in this case [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/479f02cd521a38b5e83921653f3a48e04d355915/src/datagen/java/blusunrize/immersiveengineering/data/Recipes.java#L2931).

**Comment by gorberto** [comment]
> The file you changed is automatically generated and will be overwritten the next time datagen runs (e.g. in the GH action runs once they complete). Instead you need to change the code that generates the file, in this case [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/479f02cd521a38b5e83921653f3a48e04d355915/src/datagen/java/blusunrize/immersiveengineering/data/Recipes.java#L2931).

Thanks for the explanation @malte0811!

**Comment by BluSunrize** [comment]
You also then need to execute runData and commit the changes to the generated files.
Otherwise our CI breaks.

**Comment by gorberto** [comment]
> You also then need to execute runData and commit the changes to the generated files. Otherwise our CI breaks.

Sorry about that and thank you for the explanation 😅 I'll fix the PR later this evening!

**Comment by BluSunrize** [comment]
The `src/generated/resources/.cache/cache` file has a massive diff.
Is there a change between line endings maybe?

**Comment by gorberto** [comment]
Yeah I noticed that too in [9f19e34](https://github.com/BluSunrize/ImmersiveEngineering/pull/5465/commits/9f19e3403244d7c1425d1a15004f9b5b05f93a81), but I thought I fixed that in [4836f17](https://github.com/BluSunrize/ImmersiveEngineering/pull/5465/commits/4836f172ec7fda3fa6b75c52243485c20e47d5c1) 🙁 Do you still see the large diff somewhere? `src/generated/resources/.cache/cache` only shows one update in the latest commit and the GH actions passed.

**Pull request merged**
