### PR TITLE
Fixes for the energynet, round 2

### PR DESCRIPTION
**Pull request by malte0811**
fixed some indirect connections not being used due to being considered equal to other connections without being so
fixed connections only being saved to nbt in one direction because they were considered equal to their reverse connection by `compareTo` and `equals`
fixed wires only burning in the "lowest" loaded dimension (this fix was found independently by @marcin212 as well)
this does create a merge conflict, for further information, see [here](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/)

### CODE REVIEW

**Comment by BluSunrize** [comment]
question: Why does it create a merge conflict? Why not work against the latest commit?

**Comment by malte0811** [comment]
I started working on this when @marcin212 reported the indirect connection bug, so when the commit i was working against was the latest one, and forgot to pull from your master branch in between.

**Comment by marcin212** [comment]
I looked at the conflict and is easy to repair.

**Comment by BluSunrize** [comment]
can't you just update to latest?

**Comment by malte0811** [comment]
Closing this since @marcin212 made a copy without the conflict.

**Pull request closed without merging**
