### PR TITLE
Removed debug code

### PR DESCRIPTION
**Pull request by xbony2**

### CODE REVIEW

**Comment by BluSunrize** [comment]
Already changed locally. Also, it's really pointless to do PRs for small shit like that.

**Comment by xbony2** [comment]
You probably got everything, but there's a [fair amount](https://github.com/BluSunrize/ImmersiveEngineering/search?utf8=✓&q=system.out.println&type=Code) of other debug code, so make sure you didn't miss anything ^_^

**Comment by BluSunrize** [comment]
well then maybe PR all of it out instead of doing a single line PR? ;D

**Comment by xbony2** [comment]
I was going to do that, actually, but then I'd have to pull up eclipse and everything and that would be too much effort :P

**Comment by elifoster** [comment]
If you use IntelliJ IDEA you can configure it to warn you for any System calls (or maybe it's System.out references).

**Pull request closed without merging**
