### PR TITLE
fix: Fix speelling mistake

### PR DESCRIPTION
**Pull request by FledgeXu**
There are some spelling mistakes, This PR fix it.

change `registerMagnetSupression` to `registerMagnetSuppression`
change `applyMagnetSupression` to `applyMagnetSuppression`
change `revertMagnetSupression` to `revertMagnetSuppression`

### CODE REVIEW

**Comment by malte0811** [comment]
We can't really do that in the middle of an MC version. The functions you changed are (officially) part of the API, so other mods may be using them. If we change them now those mods will crash with IE build 90. Might be a good idea to fix them as part of the 1.13 update though.

**Comment by FledgeXu** [comment]
I notice that. 
I agree that it should be fixed in 1.13 update.

**Comment by FledgeXu** [comment]
Maybe we should add `@Deprecated ` to original function and than

**Comment by FledgeXu** [comment]
Or maybe we should add `@Deprecated` to original function and then just call new function in original function?

**Comment by BluSunrize** [comment]
Closing this, since these issues should be addressed in 1.14 or other future versions

**Pull request closed without merging**
