### PR TITLE
added a creative capacitor, closes #611

### LINKED ISSUE #611: [required] unlimited energy source
required:
unlimited energy source for creative mode

### PR DESCRIPTION
**Pull request by malte0811**
This should work. Change the textures if you want, they don't look very good anyways

### CODE REVIEW

**Comment by BluSunrize** [comment]
*flails*
I never asked for this D:

**Comment by malte0811** [comment]
I just looked through the open issues... I guess i should ask before implementing new features?

**Comment by cobra** [comment]
not pink enough, needs to be visually compatible to Botania. \*scnr\*

**Comment by BluSunrize** [comment]
Well, I was just gonna be lazy and ignore it, but now that it's here, might as well =P

**Pull request merged**
