### PR TITLE
Fix crusher problems

### PR DESCRIPTION
**Pull request by cobra**
fixes all the currently known issues of the crusher, see #346.

### CODE REVIEW

**Comment by BluSunrize** [comment]
:O
Thank you. I was fearing that I'd have to assemble this one from the crusher report and the forks <3

**Comment by malte0811** [comment]
@cobra Now that i am seeing your code for the problem i solved with `hasEnergy`, i see a minor problem in it(haven't tested it yet, but i am pretty sure): if the crusher gets powered after having run out of energy, it finishes using the energy for whatever it was processing (count process down to 0) and then starts processing the same item again since active is false. That was probably why i used a new variable. Also your code syncs the nbt every tick when there is no power, the `else` should, if you ignore the other problem, be an `else if (active)`

**Comment by cobra** [comment]
@malte0811 I even asked for comments before making this PR :/
Yep, you're right. But this is easily fixed by checking `active` first before setting and updating it: https://github.com/cobra/ImmersiveEngineering/commit/1ef50b386bcc3b7509329cff9fc7284609503be2

**Comment by BluSunrize** [comment]
I implemented stuff that @malte0811 suggested with this
https://github.com/BluSunrize/ImmersiveEngineering/commit/01e384ad751770d90f6d391e95fffb27b90efc45

**Comment by cobra** [comment]
Yep, I just saw that. But you would still need to pull in this commit since that part is still broken, right? I'm just looking at your changes.

**Comment by malte0811** [comment]
@BluSunrize The issue is still there, you should probably revert a8a8c2ca1d7a412a2adbf704aaee6d92d631c7c9. You are still setting active to false when there is no power, causing the crusher to re-start processing the item it was processing once it has power and has finished consuming the energy for the first run. If whatever power supply the crusher is connected to does not produce rf every tick, the crusher will never process anything
@cobra Sorry, i did not see that problem when i had a quick look at your code before

**Comment by BluSunrize** [comment]
Gah, seriously guys, you need to get on the same level here xD
One tells me this, the other tells me that, I'm just bouncing between commits here.
If you feel it's a necessary adjustment to the code, shoot me a PR detailing the changes, but don't expect me to create code on the basis f a discussion that I haven't been following xD

**Comment by cobra** [comment]
You'll get a PR since as of now, your master branch is broken and this would be the easiest fix.

Technically, this bug (crusher appears to be running while doing nothing) is now double-dead since you've got both solutions for it, which won't conflict with each other.

**Comment by BluSunrize** [comment]
hahah, alright, glad it's done then xD

**Pull request merged**
