### PR TITLE
Update CTM implementation to the new format

### PR DESCRIPTION
**Pull request by InsomniaKitten**
All changes are listed in the commits below

### CODE REVIEW

**Comment by InsomniaKitten** [comment]
Don't merge yet! My last commit broke a thing >.<

**Comment by BluSunrize** [comment]
\o/

**Comment by BluSunrize** [comment]
You know, I don't think you accounted for the "CTM not installed" case properly :V

image

Looks a bit too high-rez, me thinks

**Comment by InsomniaKitten** [comment]
Oops, sorry! I overlooked that D:

**Pull request merged**
