### PR TITLE
OC wires support

### PR DESCRIPTION
**Pull request by marcin212**
I would need these changes to the API so that I could create an addon to IE which would add OpenComputer wires.

### CODE REVIEW

**Comment by BluSunrize** [comment]
Explanation as to why WireType is to be replaced with Connection?

**Comment by marcin212** [comment]
I need a TE on the other side to detach OCNode

**Comment by marcin212** [comment]
It is the easiest way, but You can add to API:
```
onConnectCable(Connection con)
onDisconnectCable(Connection con)
``` 
or
```
onConnectCable(IImmersiveConnectable otherside)
onDisconnectCable(IImmersiveConnectable otherside)
```

**Comment by BluSunrize** [comment]
Approved. Will be in the next build.

**Pull request merged**
