### PR TITLE
[1.11.2] Wildcard handling

### LINKED ISSUE #2138: Crash on launch
https://gist.github.com/vrork/783a3ad02be8243ebbb8e542d96ccc6e

### PR DESCRIPTION
**Pull request by Landmaster**
This fixes #2138 and also fixes Landmaster/LandCraft#3 for 1.11.2 (see #2144).

### CODE REVIEW

**Comment by Landmaster** [comment]
fixed on my side

**Comment by malte0811** [comment]
Why exactly did you close these PR's? They fix crashes with other mods as well, e.g. BoP (#2157).

**Comment by Landmaster** [comment]
@malte0811 I've reopened this pull request and #2144 in order to handle those other mods.

**Comment by Eufranio** [comment]
ETA on merging this?

**Comment by Landmaster** [comment]
@Eufranio If I'm correct, @BluSunrize would be the right person to ask.

**Comment by Eufranio** [comment]
when will there be a build?

**Comment by malte0811** [comment]
For 1.11: No ETA that I know of.
For 1.10: Probably [in the next two or three days](https://github.com/BluSunrize/ImmersiveEngineering/commit/7527fc6d1174057b32e1837f8d0f27c99f2a250e#commitcomment-22478804)

**Comment by Eufranio** [comment]
I mean jenkins build, I was testing when I got the crash of #2157 :P

**Comment by malte0811** [comment]
Jenkins builds should be created every time something is pushed to the master or 1.11.2 branch of this repo AFAIK. Jenkins build 115 (?) should have the fixes from this PR.

**Pull request merged**
