### PR TITLE
Update zh_CN.lang ---- v0.5.4

### PR DESCRIPTION
**Pull request by Joccob**

### CODE REVIEW

**Comment by bakaxyf** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/9200be056b205f7680314b9a0c9504c0cfd505f3#diff-5f481613904e64725ae03b2edaa59293L420

**Comment by 3TUSK** [comment]
Clarify: notice in line 421:
switch on--->hook up
where--->when
Personally speaking, corresponding entries *shall* change description as well.

**Comment by BluSunrize** [comment]
Can I merge this then?

**Comment by Joccob** [comment]
yes, you can

**Pull request merged**
